/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CallTrafficModal: typeof import('./src/components/modal/CallTrafficModal.vue')['default']
    CallVolume: typeof import('./src/components/modal/CallVolume.vue')['default']
    CallVolumeModal: typeof import('./src/components/modal/CallVolumeModal.vue')['default']
    CustomModal: typeof import('./src/components/modal/CustomModal.vue')['default']
    EChartComponent: typeof import('./src/components/EChartComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    LeftComponent: typeof import('./src/components/LeftComponent.vue')['default']
    MidComponent: typeof import('./src/components/MidComponent.vue')['default']
    NumberOfSeats: typeof import('./src/components/modal/NumberOfSeats.vue')['default']
    NumberOfSeatsModal: typeof import('./src/components/modal/NumberOfSeatsModal.vue')['default']
    Pie3D: typeof import('./src/components/Pie3D.vue')['default']
    PrograssBar: typeof import('./src/components/PrograssBar.vue')['default']
    RightComponent: typeof import('./src/components/RightComponent.vue')['default']
    TablePagination: typeof import('./src/components/modal/TablePagination.vue')['default']
    TodayCallTraffic: typeof import('./src/components/TodayCallTraffic.vue')['default']
    WaterOutageNotice: typeof import('./src/components/WaterOutageNotice.vue')['default']
    WaterOutageNoticeModal: typeof import('./src/components/modal/WaterOutageNoticeModal.vue')['default']
  }
}
