/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CallTrafficModal: typeof import('./src/components/modal/CallTrafficModal.vue')['default']
    CustomModal: typeof import('./src/components/modal/CustomModal.vue')['default']
    EChartComponent: typeof import('./src/components/EChartComponent.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    LeftComponent: typeof import('./src/components/LeftComponent.vue')['default']
    MidComponent: typeof import('./src/components/MidComponent.vue')['default']
    Pie3D: typeof import('./src/components/Pie3D.vue')['default']
    PrograssBar: typeof import('./src/components/PrograssBar.vue')['default']
    RightComponent: typeof import('./src/components/RightComponent.vue')['default']
    SatisfactionDialog: typeof import('./src/components/SatisfactionDialog.vue')['default']
    TablePagination: typeof import('./src/components/modal/TablePagination.vue')['default']
    TodayCallTraffic: typeof import('./src/components/TodayCallTraffic.vue')['default']
    WaterOutageNotice: typeof import('./src/components/WaterOutageNotice.vue')['default']
  }
}
